/*
 * flanker_dbService Swagger Documentation
 * Swagger API documentation for flanker_db
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.turbomobiles.FlankerAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * AddOns
 */

public class AddOns {
  @JsonProperty("frequencyId")
  private Integer frequencyId = null;

  @JsonProperty("addOnCategory")
  private AddOnCategory addOnCategory = null;

  @JsonProperty("price")
  private Integer price = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("icon")
  private String icon = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("categoryId")
  private Integer categoryId = null;

  @JsonProperty("addOnFrequency")
  private AddOnFrequency addOnFrequency = null;

  public AddOns frequencyId(Integer frequencyId) {
    this.frequencyId = frequencyId;
    return this;
  }

   /**
   * Get frequencyId
   * @return frequencyId
  **/
  public Integer getFrequencyId() {
    return frequencyId;
  }

  public void setFrequencyId(Integer frequencyId) {
    this.frequencyId = frequencyId;
  }

  public AddOns addOnCategory(AddOnCategory addOnCategory) {
    this.addOnCategory = addOnCategory;
    return this;
  }

   /**
   * Get addOnCategory
   * @return addOnCategory
  **/
  public AddOnCategory getAddOnCategory() {
    return addOnCategory;
  }

  public void setAddOnCategory(AddOnCategory addOnCategory) {
    this.addOnCategory = addOnCategory;
  }

  public AddOns price(Integer price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  public Integer getPrice() {
    return price;
  }

  public void setPrice(Integer price) {
    this.price = price;
  }

  public AddOns name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AddOns icon(String icon) {
    this.icon = icon;
    return this;
  }

   /**
   * Get icon
   * @return icon
  **/
  public String getIcon() {
    return icon;
  }

  public void setIcon(String icon) {
    this.icon = icon;
  }

  public AddOns description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AddOns id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public AddOns categoryId(Integer categoryId) {
    this.categoryId = categoryId;
    return this;
  }

   /**
   * Get categoryId
   * @return categoryId
  **/
  public Integer getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(Integer categoryId) {
    this.categoryId = categoryId;
  }

  public AddOns addOnFrequency(AddOnFrequency addOnFrequency) {
    this.addOnFrequency = addOnFrequency;
    return this;
  }

   /**
   * Get addOnFrequency
   * @return addOnFrequency
  **/
  public AddOnFrequency getAddOnFrequency() {
    return addOnFrequency;
  }

  public void setAddOnFrequency(AddOnFrequency addOnFrequency) {
    this.addOnFrequency = addOnFrequency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddOns AddOns = (AddOns) o;
    return Objects.equals(this.frequencyId, AddOns.frequencyId) &&
        Objects.equals(this.addOnCategory, AddOns.addOnCategory) &&
        Objects.equals(this.price, AddOns.price) &&
        Objects.equals(this.name, AddOns.name) &&
        Objects.equals(this.icon, AddOns.icon) &&
        Objects.equals(this.description, AddOns.description) &&
        Objects.equals(this.id, AddOns.id) &&
        Objects.equals(this.categoryId, AddOns.categoryId) &&
        Objects.equals(this.addOnFrequency, AddOns.addOnFrequency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(frequencyId, addOnCategory, price, name, icon, description, id, categoryId, addOnFrequency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddOns {\n");
    
    sb.append("    frequencyId: ").append(toIndentedString(frequencyId)).append("\n");
    sb.append("    addOnCategory: ").append(toIndentedString(addOnCategory)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    addOnFrequency: ").append(toIndentedString(addOnFrequency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
