/*
 * flanker_dbService Swagger Documentation
 * Swagger API documentation for flanker_db
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.turbomobiles.FlankerAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * BroadbandPlanFeatures
 */

public class BroadbandPlanFeatures {
  @JsonProperty("image")
  private String image = null;

  @JsonProperty("feature")
  private String feature = null;

  @JsonProperty("broadbandPlan")
  private BroadbandPlan broadbandPlan = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("broadbandPlanId")
  private Integer broadbandPlanId = null;

  public BroadbandPlanFeatures image(String image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public BroadbandPlanFeatures feature(String feature) {
    this.feature = feature;
    return this;
  }

   /**
   * Get feature
   * @return feature
  **/
  public String getFeature() {
    return feature;
  }

  public void setFeature(String feature) {
    this.feature = feature;
  }

  public BroadbandPlanFeatures broadbandPlan(BroadbandPlan broadbandPlan) {
    this.broadbandPlan = broadbandPlan;
    return this;
  }

   /**
   * Get broadbandPlan
   * @return broadbandPlan
  **/
  public BroadbandPlan getBroadbandPlan() {
    return broadbandPlan;
  }

  public void setBroadbandPlan(BroadbandPlan broadbandPlan) {
    this.broadbandPlan = broadbandPlan;
  }

  public BroadbandPlanFeatures description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public BroadbandPlanFeatures id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public BroadbandPlanFeatures broadbandPlanId(Integer broadbandPlanId) {
    this.broadbandPlanId = broadbandPlanId;
    return this;
  }

   /**
   * Get broadbandPlanId
   * @return broadbandPlanId
  **/
  public Integer getBroadbandPlanId() {
    return broadbandPlanId;
  }

  public void setBroadbandPlanId(Integer broadbandPlanId) {
    this.broadbandPlanId = broadbandPlanId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BroadbandPlanFeatures BroadbandPlanFeatures = (BroadbandPlanFeatures) o;
    return Objects.equals(this.image, BroadbandPlanFeatures.image) &&
        Objects.equals(this.feature, BroadbandPlanFeatures.feature) &&
        Objects.equals(this.broadbandPlan, BroadbandPlanFeatures.broadbandPlan) &&
        Objects.equals(this.description, BroadbandPlanFeatures.description) &&
        Objects.equals(this.id, BroadbandPlanFeatures.id) &&
        Objects.equals(this.broadbandPlanId, BroadbandPlanFeatures.broadbandPlanId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(image, feature, broadbandPlan, description, id, broadbandPlanId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BroadbandPlanFeatures {\n");
    
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    feature: ").append(toIndentedString(feature)).append("\n");
    sb.append("    broadbandPlan: ").append(toIndentedString(broadbandPlan)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    broadbandPlanId: ").append(toIndentedString(broadbandPlanId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
