/*
 * flanker_dbService Swagger Documentation
 * Swagger API documentation for flanker_db
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.turbomobiles.FlankerAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * BroadbandOrders
 */

public class BroadbandOrders {
  @JsonProperty("orderId")
  private Integer orderId = null;

  @JsonProperty("broadbandPlan")
  private BroadbandPlan broadbandPlan = null;

  @JsonProperty("orders")
  private Orders orders = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("broadbandPlanId")
  private Integer broadbandPlanId = null;

  public BroadbandOrders orderId(Integer orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  public Integer getOrderId() {
    return orderId;
  }

  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }

  public BroadbandOrders broadbandPlan(BroadbandPlan broadbandPlan) {
    this.broadbandPlan = broadbandPlan;
    return this;
  }

   /**
   * Get broadbandPlan
   * @return broadbandPlan
  **/
  public BroadbandPlan getBroadbandPlan() {
    return broadbandPlan;
  }

  public void setBroadbandPlan(BroadbandPlan broadbandPlan) {
    this.broadbandPlan = broadbandPlan;
  }

  public BroadbandOrders orders(Orders orders) {
    this.orders = orders;
    return this;
  }

   /**
   * Get orders
   * @return orders
  **/
  public Orders getOrders() {
    return orders;
  }

  public void setOrders(Orders orders) {
    this.orders = orders;
  }

  public BroadbandOrders id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public BroadbandOrders broadbandPlanId(Integer broadbandPlanId) {
    this.broadbandPlanId = broadbandPlanId;
    return this;
  }

   /**
   * Get broadbandPlanId
   * @return broadbandPlanId
  **/
  public Integer getBroadbandPlanId() {
    return broadbandPlanId;
  }

  public void setBroadbandPlanId(Integer broadbandPlanId) {
    this.broadbandPlanId = broadbandPlanId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BroadbandOrders BroadbandOrders = (BroadbandOrders) o;
    return Objects.equals(this.orderId, BroadbandOrders.orderId) &&
        Objects.equals(this.broadbandPlan, BroadbandOrders.broadbandPlan) &&
        Objects.equals(this.orders, BroadbandOrders.orders) &&
        Objects.equals(this.id, BroadbandOrders.id) &&
        Objects.equals(this.broadbandPlanId, BroadbandOrders.broadbandPlanId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, broadbandPlan, orders, id, broadbandPlanId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BroadbandOrders {\n");
    
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    broadbandPlan: ").append(toIndentedString(broadbandPlan)).append("\n");
    sb.append("    orders: ").append(toIndentedString(orders)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    broadbandPlanId: ").append(toIndentedString(broadbandPlanId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
