/*
 * flanker_dbService Swagger Documentation
 * Swagger API documentation for flanker_db
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.turbomobiles.FlankerAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
/**
 * Orders
 */

public class Orders {
  @JsonProperty("createdAt")
  private LocalDate createdAt = null;

  @JsonProperty("orderType")
  private OrderType orderType = null;

  @JsonProperty("statusId")
  private Integer statusId = null;

  @JsonProperty("orderId")
  private String orderId = null;

  @JsonProperty("customerId")
  private Integer customerId = null;

  @JsonProperty("phoneOrders")
  private PhoneOrders phoneOrders = null;

  @JsonProperty("orderStatus")
  private OrderStatus orderStatus = null;

  @JsonProperty("typeId")
  private Integer typeId = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("broadbandOrders")
  private BroadbandOrders broadbandOrders = null;

  @JsonProperty("deliveryDate")
  private LocalDate deliveryDate = null;

  @JsonProperty("customer")
  private Customer customer = null;

  public Orders createdAt(LocalDate createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  public LocalDate getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(LocalDate createdAt) {
    this.createdAt = createdAt;
  }

  public Orders orderType(OrderType orderType) {
    this.orderType = orderType;
    return this;
  }

   /**
   * Get orderType
   * @return orderType
  **/
  public OrderType getOrderType() {
    return orderType;
  }

  public void setOrderType(OrderType orderType) {
    this.orderType = orderType;
  }

  public Orders statusId(Integer statusId) {
    this.statusId = statusId;
    return this;
  }

   /**
   * Get statusId
   * @return statusId
  **/
  public Integer getStatusId() {
    return statusId;
  }

  public void setStatusId(Integer statusId) {
    this.statusId = statusId;
  }

  public Orders orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public Orders customerId(Integer customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  public Integer getCustomerId() {
    return customerId;
  }

  public void setCustomerId(Integer customerId) {
    this.customerId = customerId;
  }

  public Orders phoneOrders(PhoneOrders phoneOrders) {
    this.phoneOrders = phoneOrders;
    return this;
  }

   /**
   * Get phoneOrders
   * @return phoneOrders
  **/
  public PhoneOrders getPhoneOrders() {
    return phoneOrders;
  }

  public void setPhoneOrders(PhoneOrders phoneOrders) {
    this.phoneOrders = phoneOrders;
  }

  public Orders orderStatus(OrderStatus orderStatus) {
    this.orderStatus = orderStatus;
    return this;
  }

   /**
   * Get orderStatus
   * @return orderStatus
  **/
  public OrderStatus getOrderStatus() {
    return orderStatus;
  }

  public void setOrderStatus(OrderStatus orderStatus) {
    this.orderStatus = orderStatus;
  }

  public Orders typeId(Integer typeId) {
    this.typeId = typeId;
    return this;
  }

   /**
   * Get typeId
   * @return typeId
  **/
  public Integer getTypeId() {
    return typeId;
  }

  public void setTypeId(Integer typeId) {
    this.typeId = typeId;
  }

  public Orders id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Orders broadbandOrders(BroadbandOrders broadbandOrders) {
    this.broadbandOrders = broadbandOrders;
    return this;
  }

   /**
   * Get broadbandOrders
   * @return broadbandOrders
  **/
  public BroadbandOrders getBroadbandOrders() {
    return broadbandOrders;
  }

  public void setBroadbandOrders(BroadbandOrders broadbandOrders) {
    this.broadbandOrders = broadbandOrders;
  }

  public Orders deliveryDate(LocalDate deliveryDate) {
    this.deliveryDate = deliveryDate;
    return this;
  }

   /**
   * Get deliveryDate
   * @return deliveryDate
  **/
  public LocalDate getDeliveryDate() {
    return deliveryDate;
  }

  public void setDeliveryDate(LocalDate deliveryDate) {
    this.deliveryDate = deliveryDate;
  }

  public Orders customer(Customer customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  public Customer getCustomer() {
    return customer;
  }

  public void setCustomer(Customer customer) {
    this.customer = customer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Orders Orders = (Orders) o;
    return Objects.equals(this.createdAt, Orders.createdAt) &&
        Objects.equals(this.orderType, Orders.orderType) &&
        Objects.equals(this.statusId, Orders.statusId) &&
        Objects.equals(this.orderId, Orders.orderId) &&
        Objects.equals(this.customerId, Orders.customerId) &&
        Objects.equals(this.phoneOrders, Orders.phoneOrders) &&
        Objects.equals(this.orderStatus, Orders.orderStatus) &&
        Objects.equals(this.typeId, Orders.typeId) &&
        Objects.equals(this.id, Orders.id) &&
        Objects.equals(this.broadbandOrders, Orders.broadbandOrders) &&
        Objects.equals(this.deliveryDate, Orders.deliveryDate) &&
        Objects.equals(this.customer, Orders.customer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, orderType, statusId, orderId, customerId, phoneOrders, orderStatus, typeId, id, broadbandOrders, deliveryDate, customer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Orders {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    statusId: ").append(toIndentedString(statusId)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    phoneOrders: ").append(toIndentedString(phoneOrders)).append("\n");
    sb.append("    orderStatus: ").append(toIndentedString(orderStatus)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    broadbandOrders: ").append(toIndentedString(broadbandOrders)).append("\n");
    sb.append("    deliveryDate: ").append(toIndentedString(deliveryDate)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
