/*
 * flanker_dbService Swagger Documentation
 * Swagger API documentation for flanker_db
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.turbomobiles.FlankerAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * PhoneStorageSizes
 */

public class PhoneStorageSizes {
  @JsonProperty("sizeId")
  private Integer sizeId = null;

  @JsonProperty("phone")
  private Phone phone = null;

  @JsonProperty("storageSizes")
  private StorageSizes storageSizes = null;

  @JsonProperty("phoneId")
  private Integer phoneId = null;

  @JsonProperty("id")
  private Integer id = null;

  public PhoneStorageSizes sizeId(Integer sizeId) {
    this.sizeId = sizeId;
    return this;
  }

   /**
   * Get sizeId
   * @return sizeId
  **/
  public Integer getSizeId() {
    return sizeId;
  }

  public void setSizeId(Integer sizeId) {
    this.sizeId = sizeId;
  }

  public PhoneStorageSizes phone(Phone phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public Phone getPhone() {
    return phone;
  }

  public void setPhone(Phone phone) {
    this.phone = phone;
  }

  public PhoneStorageSizes storageSizes(StorageSizes storageSizes) {
    this.storageSizes = storageSizes;
    return this;
  }

   /**
   * Get storageSizes
   * @return storageSizes
  **/
  public StorageSizes getStorageSizes() {
    return storageSizes;
  }

  public void setStorageSizes(StorageSizes storageSizes) {
    this.storageSizes = storageSizes;
  }

  public PhoneStorageSizes phoneId(Integer phoneId) {
    this.phoneId = phoneId;
    return this;
  }

   /**
   * Get phoneId
   * @return phoneId
  **/
  public Integer getPhoneId() {
    return phoneId;
  }

  public void setPhoneId(Integer phoneId) {
    this.phoneId = phoneId;
  }

  public PhoneStorageSizes id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneStorageSizes PhoneStorageSizes = (PhoneStorageSizes) o;
    return Objects.equals(this.sizeId, PhoneStorageSizes.sizeId) &&
        Objects.equals(this.phone, PhoneStorageSizes.phone) &&
        Objects.equals(this.storageSizes, PhoneStorageSizes.storageSizes) &&
        Objects.equals(this.phoneId, PhoneStorageSizes.phoneId) &&
        Objects.equals(this.id, PhoneStorageSizes.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sizeId, phone, storageSizes, phoneId, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneStorageSizes {\n");
    
    sb.append("    sizeId: ").append(toIndentedString(sizeId)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    storageSizes: ").append(toIndentedString(storageSizes)).append("\n");
    sb.append("    phoneId: ").append(toIndentedString(phoneId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
