/*
 * flanker_dbService Swagger Documentation
 * Swagger API documentation for flanker_db
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.turbomobiles.FlankerAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * PhonePricePlanFeatures
 */

public class PhonePricePlanFeatures {
  @JsonProperty("phonePricePlan")
  private PhonePricePlan phonePricePlan = null;

  @JsonProperty("pricePlanCategoryId")
  private Integer pricePlanCategoryId = null;

  @JsonProperty("pricePlanCategory")
  private PricePlanCategory pricePlanCategory = null;

  @JsonProperty("feature")
  private String feature = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("pricePlanId")
  private Integer pricePlanId = null;

  public PhonePricePlanFeatures phonePricePlan(PhonePricePlan phonePricePlan) {
    this.phonePricePlan = phonePricePlan;
    return this;
  }

   /**
   * Get phonePricePlan
   * @return phonePricePlan
  **/
  public PhonePricePlan getPhonePricePlan() {
    return phonePricePlan;
  }

  public void setPhonePricePlan(PhonePricePlan phonePricePlan) {
    this.phonePricePlan = phonePricePlan;
  }

  public PhonePricePlanFeatures pricePlanCategoryId(Integer pricePlanCategoryId) {
    this.pricePlanCategoryId = pricePlanCategoryId;
    return this;
  }

   /**
   * Get pricePlanCategoryId
   * @return pricePlanCategoryId
  **/
  public Integer getPricePlanCategoryId() {
    return pricePlanCategoryId;
  }

  public void setPricePlanCategoryId(Integer pricePlanCategoryId) {
    this.pricePlanCategoryId = pricePlanCategoryId;
  }

  public PhonePricePlanFeatures pricePlanCategory(PricePlanCategory pricePlanCategory) {
    this.pricePlanCategory = pricePlanCategory;
    return this;
  }

   /**
   * Get pricePlanCategory
   * @return pricePlanCategory
  **/
  public PricePlanCategory getPricePlanCategory() {
    return pricePlanCategory;
  }

  public void setPricePlanCategory(PricePlanCategory pricePlanCategory) {
    this.pricePlanCategory = pricePlanCategory;
  }

  public PhonePricePlanFeatures feature(String feature) {
    this.feature = feature;
    return this;
  }

   /**
   * Get feature
   * @return feature
  **/
  public String getFeature() {
    return feature;
  }

  public void setFeature(String feature) {
    this.feature = feature;
  }

  public PhonePricePlanFeatures id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public PhonePricePlanFeatures pricePlanId(Integer pricePlanId) {
    this.pricePlanId = pricePlanId;
    return this;
  }

   /**
   * Get pricePlanId
   * @return pricePlanId
  **/
  public Integer getPricePlanId() {
    return pricePlanId;
  }

  public void setPricePlanId(Integer pricePlanId) {
    this.pricePlanId = pricePlanId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhonePricePlanFeatures PhonePricePlanFeatures = (PhonePricePlanFeatures) o;
    return Objects.equals(this.phonePricePlan, PhonePricePlanFeatures.phonePricePlan) &&
        Objects.equals(this.pricePlanCategoryId, PhonePricePlanFeatures.pricePlanCategoryId) &&
        Objects.equals(this.pricePlanCategory, PhonePricePlanFeatures.pricePlanCategory) &&
        Objects.equals(this.feature, PhonePricePlanFeatures.feature) &&
        Objects.equals(this.id, PhonePricePlanFeatures.id) &&
        Objects.equals(this.pricePlanId, PhonePricePlanFeatures.pricePlanId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phonePricePlan, pricePlanCategoryId, pricePlanCategory, feature, id, pricePlanId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhonePricePlanFeatures {\n");
    
    sb.append("    phonePricePlan: ").append(toIndentedString(phonePricePlan)).append("\n");
    sb.append("    pricePlanCategoryId: ").append(toIndentedString(pricePlanCategoryId)).append("\n");
    sb.append("    pricePlanCategory: ").append(toIndentedString(pricePlanCategory)).append("\n");
    sb.append("    feature: ").append(toIndentedString(feature)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    pricePlanId: ").append(toIndentedString(pricePlanId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
