/*
 * flanker_dbService Swagger Documentation
 * Swagger API documentation for flanker_db
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.turbomobiles.FlankerAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * PhoneOrders
 */

public class PhoneOrders {
  @JsonProperty("simType")
  private String simType = null;

  @JsonProperty("phonePricePlan")
  private PhonePricePlan phonePricePlan = null;

  @JsonProperty("phoneModel")
  private PhoneModel phoneModel = null;

  @JsonProperty("orderId")
  private Integer orderId = null;

  @JsonProperty("price")
  private Double price = null;

  @JsonProperty("phoneVariantId")
  private Integer phoneVariantId = null;

  @JsonProperty("phoneModelId")
  private Integer phoneModelId = null;

  @JsonProperty("phonePlanId")
  private Integer phonePlanId = null;

  @JsonProperty("orders")
  private Orders orders = null;

  @JsonProperty("phoneVariant")
  private PhoneVariant phoneVariant = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("isSimActivated")
  private Boolean isSimActivated = null;

  public PhoneOrders simType(String simType) {
    this.simType = simType;
    return this;
  }

   /**
   * Get simType
   * @return simType
  **/
  public String getSimType() {
    return simType;
  }

  public void setSimType(String simType) {
    this.simType = simType;
  }

  public PhoneOrders phonePricePlan(PhonePricePlan phonePricePlan) {
    this.phonePricePlan = phonePricePlan;
    return this;
  }

   /**
   * Get phonePricePlan
   * @return phonePricePlan
  **/
  public PhonePricePlan getPhonePricePlan() {
    return phonePricePlan;
  }

  public void setPhonePricePlan(PhonePricePlan phonePricePlan) {
    this.phonePricePlan = phonePricePlan;
  }

  public PhoneOrders phoneModel(PhoneModel phoneModel) {
    this.phoneModel = phoneModel;
    return this;
  }

   /**
   * Get phoneModel
   * @return phoneModel
  **/
  public PhoneModel getPhoneModel() {
    return phoneModel;
  }

  public void setPhoneModel(PhoneModel phoneModel) {
    this.phoneModel = phoneModel;
  }

  public PhoneOrders orderId(Integer orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  public Integer getOrderId() {
    return orderId;
  }

  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }

  public PhoneOrders price(Double price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }

  public PhoneOrders phoneVariantId(Integer phoneVariantId) {
    this.phoneVariantId = phoneVariantId;
    return this;
  }

   /**
   * Get phoneVariantId
   * @return phoneVariantId
  **/
  public Integer getPhoneVariantId() {
    return phoneVariantId;
  }

  public void setPhoneVariantId(Integer phoneVariantId) {
    this.phoneVariantId = phoneVariantId;
  }

  public PhoneOrders phoneModelId(Integer phoneModelId) {
    this.phoneModelId = phoneModelId;
    return this;
  }

   /**
   * Get phoneModelId
   * @return phoneModelId
  **/
  public Integer getPhoneModelId() {
    return phoneModelId;
  }

  public void setPhoneModelId(Integer phoneModelId) {
    this.phoneModelId = phoneModelId;
  }

  public PhoneOrders phonePlanId(Integer phonePlanId) {
    this.phonePlanId = phonePlanId;
    return this;
  }

   /**
   * Get phonePlanId
   * @return phonePlanId
  **/
  public Integer getPhonePlanId() {
    return phonePlanId;
  }

  public void setPhonePlanId(Integer phonePlanId) {
    this.phonePlanId = phonePlanId;
  }

  public PhoneOrders orders(Orders orders) {
    this.orders = orders;
    return this;
  }

   /**
   * Get orders
   * @return orders
  **/
  public Orders getOrders() {
    return orders;
  }

  public void setOrders(Orders orders) {
    this.orders = orders;
  }

  public PhoneOrders phoneVariant(PhoneVariant phoneVariant) {
    this.phoneVariant = phoneVariant;
    return this;
  }

   /**
   * Get phoneVariant
   * @return phoneVariant
  **/
  public PhoneVariant getPhoneVariant() {
    return phoneVariant;
  }

  public void setPhoneVariant(PhoneVariant phoneVariant) {
    this.phoneVariant = phoneVariant;
  }

  public PhoneOrders id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public PhoneOrders isSimActivated(Boolean isSimActivated) {
    this.isSimActivated = isSimActivated;
    return this;
  }

   /**
   * Get isSimActivated
   * @return isSimActivated
  **/
  public Boolean isIsSimActivated() {
    return isSimActivated;
  }

  public void setIsSimActivated(Boolean isSimActivated) {
    this.isSimActivated = isSimActivated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneOrders PhoneOrders = (PhoneOrders) o;
    return Objects.equals(this.simType, PhoneOrders.simType) &&
        Objects.equals(this.phonePricePlan, PhoneOrders.phonePricePlan) &&
        Objects.equals(this.phoneModel, PhoneOrders.phoneModel) &&
        Objects.equals(this.orderId, PhoneOrders.orderId) &&
        Objects.equals(this.price, PhoneOrders.price) &&
        Objects.equals(this.phoneVariantId, PhoneOrders.phoneVariantId) &&
        Objects.equals(this.phoneModelId, PhoneOrders.phoneModelId) &&
        Objects.equals(this.phonePlanId, PhoneOrders.phonePlanId) &&
        Objects.equals(this.orders, PhoneOrders.orders) &&
        Objects.equals(this.phoneVariant, PhoneOrders.phoneVariant) &&
        Objects.equals(this.id, PhoneOrders.id) &&
        Objects.equals(this.isSimActivated, PhoneOrders.isSimActivated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(simType, phonePricePlan, phoneModel, orderId, price, phoneVariantId, phoneModelId, phonePlanId, orders, phoneVariant, id, isSimActivated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneOrders {\n");
    
    sb.append("    simType: ").append(toIndentedString(simType)).append("\n");
    sb.append("    phonePricePlan: ").append(toIndentedString(phonePricePlan)).append("\n");
    sb.append("    phoneModel: ").append(toIndentedString(phoneModel)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    phoneVariantId: ").append(toIndentedString(phoneVariantId)).append("\n");
    sb.append("    phoneModelId: ").append(toIndentedString(phoneModelId)).append("\n");
    sb.append("    phonePlanId: ").append(toIndentedString(phonePlanId)).append("\n");
    sb.append("    orders: ").append(toIndentedString(orders)).append("\n");
    sb.append("    phoneVariant: ").append(toIndentedString(phoneVariant)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isSimActivated: ").append(toIndentedString(isSimActivated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
