/*
 * flanker_dbService Swagger Documentation
 * Swagger API documentation for flanker_db
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.turbomobiles.FlankerAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * PhoneSpecs
 */

public class PhoneSpecs {
  @JsonProperty("specName")
  private String specName = null;

  @JsonProperty("phone")
  private Phone phone = null;

  @JsonProperty("specValue")
  private String specValue = null;

  @JsonProperty("phoneId")
  private Integer phoneId = null;

  @JsonProperty("id")
  private Integer id = null;

  public PhoneSpecs specName(String specName) {
    this.specName = specName;
    return this;
  }

   /**
   * Get specName
   * @return specName
  **/
  public String getSpecName() {
    return specName;
  }

  public void setSpecName(String specName) {
    this.specName = specName;
  }

  public PhoneSpecs phone(Phone phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public Phone getPhone() {
    return phone;
  }

  public void setPhone(Phone phone) {
    this.phone = phone;
  }

  public PhoneSpecs specValue(String specValue) {
    this.specValue = specValue;
    return this;
  }

   /**
   * Get specValue
   * @return specValue
  **/
  public String getSpecValue() {
    return specValue;
  }

  public void setSpecValue(String specValue) {
    this.specValue = specValue;
  }

  public PhoneSpecs phoneId(Integer phoneId) {
    this.phoneId = phoneId;
    return this;
  }

   /**
   * Get phoneId
   * @return phoneId
  **/
  public Integer getPhoneId() {
    return phoneId;
  }

  public void setPhoneId(Integer phoneId) {
    this.phoneId = phoneId;
  }

  public PhoneSpecs id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneSpecs PhoneSpecs = (PhoneSpecs) o;
    return Objects.equals(this.specName, PhoneSpecs.specName) &&
        Objects.equals(this.phone, PhoneSpecs.phone) &&
        Objects.equals(this.specValue, PhoneSpecs.specValue) &&
        Objects.equals(this.phoneId, PhoneSpecs.phoneId) &&
        Objects.equals(this.id, PhoneSpecs.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(specName, phone, specValue, phoneId, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneSpecs {\n");
    
    sb.append("    specName: ").append(toIndentedString(specName)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    specValue: ").append(toIndentedString(specValue)).append("\n");
    sb.append("    phoneId: ").append(toIndentedString(phoneId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
