/*
 * flanker_dbService Swagger Documentation
 * Swagger API documentation for flanker_db
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.turbomobiles.FlankerAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * PhoneVariantPictures
 */

public class PhoneVariantPictures {
  @JsonProperty("image")
  private String image = null;

  @JsonProperty("phoneColors")
  private PhoneColors phoneColors = null;

  @JsonProperty("phoneColorId")
  private Integer phoneColorId = null;

  @JsonProperty("id")
  private Integer id = null;

  public PhoneVariantPictures image(String image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public PhoneVariantPictures phoneColors(PhoneColors phoneColors) {
    this.phoneColors = phoneColors;
    return this;
  }

   /**
   * Get phoneColors
   * @return phoneColors
  **/
  public PhoneColors getPhoneColors() {
    return phoneColors;
  }

  public void setPhoneColors(PhoneColors phoneColors) {
    this.phoneColors = phoneColors;
  }

  public PhoneVariantPictures phoneColorId(Integer phoneColorId) {
    this.phoneColorId = phoneColorId;
    return this;
  }

   /**
   * Get phoneColorId
   * @return phoneColorId
  **/
  public Integer getPhoneColorId() {
    return phoneColorId;
  }

  public void setPhoneColorId(Integer phoneColorId) {
    this.phoneColorId = phoneColorId;
  }

  public PhoneVariantPictures id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneVariantPictures PhoneVariantPictures = (PhoneVariantPictures) o;
    return Objects.equals(this.image, PhoneVariantPictures.image) &&
        Objects.equals(this.phoneColors, PhoneVariantPictures.phoneColors) &&
        Objects.equals(this.phoneColorId, PhoneVariantPictures.phoneColorId) &&
        Objects.equals(this.id, PhoneVariantPictures.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(image, phoneColors, phoneColorId, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneVariantPictures {\n");
    
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    phoneColors: ").append(toIndentedString(phoneColors)).append("\n");
    sb.append("    phoneColorId: ").append(toIndentedString(phoneColorId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
