/*
 * flanker_dbService Swagger Documentation
 * Swagger API documentation for flanker_db
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.turbomobiles.FlankerAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * PhoneModel
 */

public class PhoneModel {
  @JsonProperty("phoneBrand")
  private PhoneBrand phoneBrand = null;

  @JsonProperty("brandId")
  private Integer brandId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("id")
  private Integer id = null;

  public PhoneModel phoneBrand(PhoneBrand phoneBrand) {
    this.phoneBrand = phoneBrand;
    return this;
  }

   /**
   * Get phoneBrand
   * @return phoneBrand
  **/
  public PhoneBrand getPhoneBrand() {
    return phoneBrand;
  }

  public void setPhoneBrand(PhoneBrand phoneBrand) {
    this.phoneBrand = phoneBrand;
  }

  public PhoneModel brandId(Integer brandId) {
    this.brandId = brandId;
    return this;
  }

   /**
   * Get brandId
   * @return brandId
  **/
  public Integer getBrandId() {
    return brandId;
  }

  public void setBrandId(Integer brandId) {
    this.brandId = brandId;
  }

  public PhoneModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PhoneModel id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneModel PhoneModel = (PhoneModel) o;
    return Objects.equals(this.phoneBrand, PhoneModel.phoneBrand) &&
        Objects.equals(this.brandId, PhoneModel.brandId) &&
        Objects.equals(this.name, PhoneModel.name) &&
        Objects.equals(this.id, PhoneModel.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phoneBrand, brandId, name, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneModel {\n");
    
    sb.append("    phoneBrand: ").append(toIndentedString(phoneBrand)).append("\n");
    sb.append("    brandId: ").append(toIndentedString(brandId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
