/*
 * flanker_dbService Swagger Documentation
 * Swagger API documentation for flanker_db
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.turbomobiles.FlankerAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * PhoneVariant
 */

public class PhoneVariant {
  @JsonProperty("phoneColors")
  private PhoneColors phoneColors = null;

  @JsonProperty("phoneStorageSizes")
  private PhoneStorageSizes phoneStorageSizes = null;

  @JsonProperty("phone")
  private Phone phone = null;

  @JsonProperty("price")
  private Integer price = null;

  @JsonProperty("phoneColorId")
  private Integer phoneColorId = null;

  @JsonProperty("phoneId")
  private Integer phoneId = null;

  @JsonProperty("phoneStorageSizeId")
  private Integer phoneStorageSizeId = null;

  @JsonProperty("id")
  private Integer id = null;

  public PhoneVariant phoneColors(PhoneColors phoneColors) {
    this.phoneColors = phoneColors;
    return this;
  }

   /**
   * Get phoneColors
   * @return phoneColors
  **/
  public PhoneColors getPhoneColors() {
    return phoneColors;
  }

  public void setPhoneColors(PhoneColors phoneColors) {
    this.phoneColors = phoneColors;
  }

  public PhoneVariant phoneStorageSizes(PhoneStorageSizes phoneStorageSizes) {
    this.phoneStorageSizes = phoneStorageSizes;
    return this;
  }

   /**
   * Get phoneStorageSizes
   * @return phoneStorageSizes
  **/
  public PhoneStorageSizes getPhoneStorageSizes() {
    return phoneStorageSizes;
  }

  public void setPhoneStorageSizes(PhoneStorageSizes phoneStorageSizes) {
    this.phoneStorageSizes = phoneStorageSizes;
  }

  public PhoneVariant phone(Phone phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public Phone getPhone() {
    return phone;
  }

  public void setPhone(Phone phone) {
    this.phone = phone;
  }

  public PhoneVariant price(Integer price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  public Integer getPrice() {
    return price;
  }

  public void setPrice(Integer price) {
    this.price = price;
  }

  public PhoneVariant phoneColorId(Integer phoneColorId) {
    this.phoneColorId = phoneColorId;
    return this;
  }

   /**
   * Get phoneColorId
   * @return phoneColorId
  **/
  public Integer getPhoneColorId() {
    return phoneColorId;
  }

  public void setPhoneColorId(Integer phoneColorId) {
    this.phoneColorId = phoneColorId;
  }

  public PhoneVariant phoneId(Integer phoneId) {
    this.phoneId = phoneId;
    return this;
  }

   /**
   * Get phoneId
   * @return phoneId
  **/
  public Integer getPhoneId() {
    return phoneId;
  }

  public void setPhoneId(Integer phoneId) {
    this.phoneId = phoneId;
  }

  public PhoneVariant phoneStorageSizeId(Integer phoneStorageSizeId) {
    this.phoneStorageSizeId = phoneStorageSizeId;
    return this;
  }

   /**
   * Get phoneStorageSizeId
   * @return phoneStorageSizeId
  **/
  public Integer getPhoneStorageSizeId() {
    return phoneStorageSizeId;
  }

  public void setPhoneStorageSizeId(Integer phoneStorageSizeId) {
    this.phoneStorageSizeId = phoneStorageSizeId;
  }

  public PhoneVariant id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneVariant PhoneVariant = (PhoneVariant) o;
    return Objects.equals(this.phoneColors, PhoneVariant.phoneColors) &&
        Objects.equals(this.phoneStorageSizes, PhoneVariant.phoneStorageSizes) &&
        Objects.equals(this.phone, PhoneVariant.phone) &&
        Objects.equals(this.price, PhoneVariant.price) &&
        Objects.equals(this.phoneColorId, PhoneVariant.phoneColorId) &&
        Objects.equals(this.phoneId, PhoneVariant.phoneId) &&
        Objects.equals(this.phoneStorageSizeId, PhoneVariant.phoneStorageSizeId) &&
        Objects.equals(this.id, PhoneVariant.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phoneColors, phoneStorageSizes, phone, price, phoneColorId, phoneId, phoneStorageSizeId, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneVariant {\n");
    
    sb.append("    phoneColors: ").append(toIndentedString(phoneColors)).append("\n");
    sb.append("    phoneStorageSizes: ").append(toIndentedString(phoneStorageSizes)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    phoneColorId: ").append(toIndentedString(phoneColorId)).append("\n");
    sb.append("    phoneId: ").append(toIndentedString(phoneId)).append("\n");
    sb.append("    phoneStorageSizeId: ").append(toIndentedString(phoneStorageSizeId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
