/*
 * flanker_dbService Swagger Documentation
 * Swagger API documentation for flanker_db
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.turbomobiles.FlankerAPI.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
/**
 * Phone
 */

public class Phone {
  @JsonProperty("phoneStorageSizeses")
  private List<PhoneStorageSizes> phoneStorageSizeses = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("baseImage")
  private String baseImage = null;

  @JsonProperty("phoneColorses")
  private List<PhoneColors> phoneColorses = null;

  @JsonProperty("company")
  private String company = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("startingPrice")
  private Integer startingPrice = null;

  public Phone phoneStorageSizeses(List<PhoneStorageSizes> phoneStorageSizeses) {
    this.phoneStorageSizeses = phoneStorageSizeses;
    return this;
  }

  public Phone addPhoneStorageSizesesItem(PhoneStorageSizes phoneStorageSizesesItem) {
    if (this.phoneStorageSizeses == null) {
      this.phoneStorageSizeses = new ArrayList<>();
    }
    this.phoneStorageSizeses.add(phoneStorageSizesesItem);
    return this;
  }

   /**
   * Get phoneStorageSizeses
   * @return phoneStorageSizeses
  **/
  public List<PhoneStorageSizes> getPhoneStorageSizeses() {
    return phoneStorageSizeses;
  }

  public void setPhoneStorageSizeses(List<PhoneStorageSizes> phoneStorageSizeses) {
    this.phoneStorageSizeses = phoneStorageSizeses;
  }

  public Phone name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Phone baseImage(String baseImage) {
    this.baseImage = baseImage;
    return this;
  }

   /**
   * Get baseImage
   * @return baseImage
  **/
  public String getBaseImage() {
    return baseImage;
  }

  public void setBaseImage(String baseImage) {
    this.baseImage = baseImage;
  }

  public Phone phoneColorses(List<PhoneColors> phoneColorses) {
    this.phoneColorses = phoneColorses;
    return this;
  }

  public Phone addPhoneColorsesItem(PhoneColors phoneColorsesItem) {
    if (this.phoneColorses == null) {
      this.phoneColorses = new ArrayList<>();
    }
    this.phoneColorses.add(phoneColorsesItem);
    return this;
  }

   /**
   * Get phoneColorses
   * @return phoneColorses
  **/
  public List<PhoneColors> getPhoneColorses() {
    return phoneColorses;
  }

  public void setPhoneColorses(List<PhoneColors> phoneColorses) {
    this.phoneColorses = phoneColorses;
  }

  public Phone company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public Phone id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Phone startingPrice(Integer startingPrice) {
    this.startingPrice = startingPrice;
    return this;
  }

   /**
   * Get startingPrice
   * @return startingPrice
  **/
  public Integer getStartingPrice() {
    return startingPrice;
  }

  public void setStartingPrice(Integer startingPrice) {
    this.startingPrice = startingPrice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Phone Phone = (Phone) o;
    return Objects.equals(this.phoneStorageSizeses, Phone.phoneStorageSizeses) &&
        Objects.equals(this.name, Phone.name) &&
        Objects.equals(this.baseImage, Phone.baseImage) &&
        Objects.equals(this.phoneColorses, Phone.phoneColorses) &&
        Objects.equals(this.company, Phone.company) &&
        Objects.equals(this.id, Phone.id) &&
        Objects.equals(this.startingPrice, Phone.startingPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phoneStorageSizeses, name, baseImage, phoneColorses, company, id, startingPrice);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Phone {\n");
    
    sb.append("    phoneStorageSizeses: ").append(toIndentedString(phoneStorageSizeses)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    baseImage: ").append(toIndentedString(baseImage)).append("\n");
    sb.append("    phoneColorses: ").append(toIndentedString(phoneColorses)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    startingPrice: ").append(toIndentedString(startingPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
