/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.turbomobiles.GetUserByEmail.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.turbomobiles.GetUserByEmail.model.JavaLangObject;
import com.wavemaker.turbomobiles.GetUserByEmail.model.ResponseContentEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("number")
  private Integer number = null;

  @JsonProperty("last")
  private Boolean last = null;

  @JsonProperty("size")
  private Integer size = null;

  @JsonProperty("numberOfElements")
  private Integer numberOfElements = null;

  @JsonProperty("totalPages")
  private Integer totalPages = null;

  @JsonProperty("sort")
  private List<JavaLangObject> sort = new ArrayList<>();

  @JsonProperty("content")
  private List<ResponseContentEntryItem> content = new ArrayList<>();

  @JsonProperty("first")
  private Boolean first = null;

  @JsonProperty("totalElements")
  private Integer totalElements = null;

  @JsonProperty("empty")
  private Boolean empty = null;

  public RootResponse number(Integer number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  public Integer getNumber() {
    return number;
  }

  public void setNumber(Integer number) {
    this.number = number;
  }

  public RootResponse last(Boolean last) {
    this.last = last;
    return this;
  }

   /**
   * Get last
   * @return last
  **/
  public Boolean isLast() {
    return last;
  }

  public void setLast(Boolean last) {
    this.last = last;
  }

  public RootResponse size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public RootResponse numberOfElements(Integer numberOfElements) {
    this.numberOfElements = numberOfElements;
    return this;
  }

   /**
   * Get numberOfElements
   * @return numberOfElements
  **/
  public Integer getNumberOfElements() {
    return numberOfElements;
  }

  public void setNumberOfElements(Integer numberOfElements) {
    this.numberOfElements = numberOfElements;
  }

  public RootResponse totalPages(Integer totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Get totalPages
   * @return totalPages
  **/
  public Integer getTotalPages() {
    return totalPages;
  }

  public void setTotalPages(Integer totalPages) {
    this.totalPages = totalPages;
  }

  public RootResponse sort(List<JavaLangObject> sort) {
    this.sort = sort;
    return this;
  }

  public RootResponse addSortItem(JavaLangObject sortItem) {
    this.sort.add(sortItem);
    return this;
  }

   /**
   * Get sort
   * @return sort
  **/
  public List<JavaLangObject> getSort() {
    return sort;
  }

  public void setSort(List<JavaLangObject> sort) {
    this.sort = sort;
  }

  public RootResponse content(List<ResponseContentEntryItem> content) {
    this.content = content;
    return this;
  }

  public RootResponse addContentItem(ResponseContentEntryItem contentItem) {
    this.content.add(contentItem);
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  public List<ResponseContentEntryItem> getContent() {
    return content;
  }

  public void setContent(List<ResponseContentEntryItem> content) {
    this.content = content;
  }

  public RootResponse first(Boolean first) {
    this.first = first;
    return this;
  }

   /**
   * Get first
   * @return first
  **/
  public Boolean isFirst() {
    return first;
  }

  public void setFirst(Boolean first) {
    this.first = first;
  }

  public RootResponse totalElements(Integer totalElements) {
    this.totalElements = totalElements;
    return this;
  }

   /**
   * Get totalElements
   * @return totalElements
  **/
  public Integer getTotalElements() {
    return totalElements;
  }

  public void setTotalElements(Integer totalElements) {
    this.totalElements = totalElements;
  }

  public RootResponse empty(Boolean empty) {
    this.empty = empty;
    return this;
  }

   /**
   * Get empty
   * @return empty
  **/
  public Boolean isEmpty() {
    return empty;
  }

  public void setEmpty(Boolean empty) {
    this.empty = empty;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.number, RootResponse.number) &&
        Objects.equals(this.last, RootResponse.last) &&
        Objects.equals(this.size, RootResponse.size) &&
        Objects.equals(this.numberOfElements, RootResponse.numberOfElements) &&
        Objects.equals(this.totalPages, RootResponse.totalPages) &&
        Objects.equals(this.sort, RootResponse.sort) &&
        Objects.equals(this.content, RootResponse.content) &&
        Objects.equals(this.first, RootResponse.first) &&
        Objects.equals(this.totalElements, RootResponse.totalElements) &&
        Objects.equals(this.empty, RootResponse.empty);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, last, size, numberOfElements, totalPages, sort, content, first, totalElements, empty);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    last: ").append(toIndentedString(last)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    numberOfElements: ").append(toIndentedString(numberOfElements)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    first: ").append(toIndentedString(first)).append("\n");
    sb.append("    totalElements: ").append(toIndentedString(totalElements)).append("\n");
    sb.append("    empty: ").append(toIndentedString(empty)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
